apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXBPVTlzb0U1MGM0d0M4WGxHQ3k1TWdTaWtiMHEyY0llSWRVbnNJVDMyc0lxClhrbFV6V2d0c0ZZbm5kN3VHb0Rod05ZQWh1NzE1c1QrcjJGL1E1SHJBSWZ4TTdCVzJUenIyUWhoTTBvTHI3SW0KVzhpdVFsT0ZENDNnUm9mN29hdHhvMzl5Y1NpeHNxM1l5TFhsUUFRRWxhbkFrUUM1bndrWXRWWkNqc2cyQ1VuQwo3UFppWDYrNnZnUGxjM1VTaWd2NW4wZ1IrcUlCRGpNbEgxMklia0JJRlBjeHM4Z3JOUHNFM3h1azdhV3liYlBhCjE1K2UyN09JTWJsbVorZ2c3azMzelV0RGRkTFYrcGtZWVlFdjJudEw0VEdrVG16eTVJSW5GeVNlbVVqRjVjZkUKaDdjM1JQN1lGMmhnTktzaXB5RFZkU09sMWxUbGxrb1E0d2VDeTFPS213SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBR3A2akliN0VLSVBrZ3VsZHJEdVhiTjNtdkJKUHQyRXpOb3ZYbWlSaHRyMXdvcTZwZXpkCjJzWmdUcll6WWdrVFRRUnN5RXZWVXgwd1JvWTV6bmV4U09mMDBkV1V3OURraktNNGJpZmJ0WkhwL0NySElPWlMKY2NHRkVpQUNJYVNaYUZoaG14MVRPMVhJQkdqdXBDZkFjTWRQWE5CWmxGQnhnUmMzRWxWbzVQdEZHTHYzbjhsMwp3SWgxZzlkS1dXcE96Yk1RWHcwS1lXS2dwNFZLZFViNE5keDlwUlFVUDlLOVBMUXBsU3d3Yk1LdjNtcGFpU2IwCjZhMkRRczNhTTNjY29QUlN3L1VIaVEvUXhoc0JWOUFiNktTSmhVRmt3WGQzK0ZWNU9TUmxNQVJ4MEZsclNEMWEKeUlhKzJQdWtuUFVVUVlRUDZPM0M5UElHMXppU3lKUzBSMjA9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth
