apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXZVU05KNDRXdExqSVd2WWNmakVUZjIxMFg4ZEFWdWY0eWdKMVJTQWlpcElyCld6KzlTeEtMVUNoN0pqTXpRL213U3IyMDZIekM5RmtLZEI4elVBUFk0REUxRDh4Z2FlYkVVRW9hdGlMUzM3dlYKOGEzQzcveC9lYzkzMVgwSC8zRnY0MnpuQXhRNkNJSGtXS2Vkak1rZ2V4YVgxS084RGYwdmNaaG1tVnB2SzRkVwpSekRjY0xHb3lwSTFUTXlIdjdUb1RzOUNiVXFNSzVxazUwbDNPQmZ4M1RrckNDVlRaOVhwRkVpSVZRK2Z0MitvCk9MTkpGWitXbGV5ZERKakRRZXFzd29ldmtqWHZqUkcwQkFvdmFyUnVpdzk2eDA4SnBoMmVFSmk5R0JzSmZ1bS8KNUg3U0tacWt4TGtPaUxKcnVFdVBxdWVoNDFPM0U0alBoRzA0Vk83UXJRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQ1pxZGJnRW5yanpYWkJUK285ZWRFOHc3eHczei84ZWg2Yml1UWZKd3ZvcnBOZjhHc0tWCkFRcU0zM1BSNGRYUHZnTmRUOCtkUmRPeUtHVDBRUStXUXppR2g3dHZzRnlJeFVwQ21hYWJraEdVRXRMWnM4SHcKTVY0TkZYMGwxY2VDNXpUZnAycHNScDRKelJ1YWdpZWYrMlBZZGZjQ0R0amNWVXJKcjhMTzFVZS9ORGlxZWhrbQo2V2VoRHVsb09qK3VYUC9aYUFWZWxRU1B4eDJHVndXYjd3YllKTXdVbUQyaGhrQ1ZrV0hBZXU3TmtnYkZzTis4CmJnNlJEM3NpbUpQL2I3SDBoTDFUYXY1REE0ZFVES3ZPTDFrb0lmZGEwekNmRUFkWERsbmtFMDNIcTdkakxkQ1AKT0tOdklqQWlrZk50cXphOHBlblVWeTlES2w0NEF4MXYwZzA9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth
