apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp-deply
    name: my-app
  name: webapp-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30009
  type: NodePort  
  selector:
    app: myapp-deply
    name: my-app
