apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp
    type: front-end
  name: myapp-deployment-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30009
  selector:
    type: front-end
  type: NodePort
status:
  loadBalancer: {}
