apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default
spec:
  type: NodePort
  ports:
    - nodePort: 30080
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: webapp-pod
