apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp-deply
    name: my-app
  name: myapp-deply
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp-deply
      name: my-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp-deply
        name: my-app
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
