apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp-deply
    name: my-app
  name: myapp-deply
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30009
  selector:
    app: myapp-deply
    name: my-app
status:
  loadBalancer: {}
