apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end

spec:
 template:

    metadata:
     name: myapp-pod
     labels:
       app: myapp
    spec:
      containers:
        - name: nginx-php-hostname
          image: ashkarstudy/nginx-php-hostname:v1

 replicas: 3
 selector:
   matchLabels:
     type: front-end
