apiVersion: v1
kind: Pod
metadata:
  name: hr-app

spec:
  containers:
    - image: nginx:alpine
      name: hr-app
      ports:
        - containerPort: 80
          protocol: TCP
  nodeName: node02
