apiVersion: v1
kind: Pod
metadata:
  name: pod-limit
spec:
  containers:
    - image: nginx
      name:  nginx
      resources:
        limits:
          memory: 20Mi
        requests:
          memory: 10Mi
